import { defineConfig } from 'tsdown';
import { tsupCompatOutExtensions } from "../../tsdown.shared.mjs";

export default defineConfig({
  outExtensions: tsupCompatOutExtensions,
  tsconfig: 'tsconfig.build.json',
  entry: {
    index: 'src/index.ts',
    lambda: 'src/lambda.ts',
    'lambda-auto': 'src/lambda/auto.ts',
    sdk: 'src/sdk.ts',
    s3: 'src/s3.ts',
    dynamodb: 'src/dynamodb.ts',
    sqs: 'src/sqs.ts',
    sns: 'src/sns.ts',
    kinesis: 'src/kinesis.ts',
    'step-functions': 'src/step-functions.ts',
    eventbridge: 'src/eventbridge.ts',
    xray: 'src/xray.ts',
    cloudwatch: 'src/cloudwatch/index.ts',
    testing: 'src/testing.ts',
    attributes: 'src/attributes.ts',
  },
  format: ['esm', 'cjs'],
  dts: true,
  sourcemap: true,
  outDir: 'dist',
  clean: true,
  treeshake: true,
  minify: false,
  deps: {
    neverBundle: [
    'autotel',
    '@aws-sdk/client-s3',
    '@aws-sdk/client-dynamodb',
    '@aws-sdk/client-sqs',
    '@aws-sdk/client-sns',
    '@aws-sdk/client-kinesis',
    '@aws-sdk/client-sfn',
    '@aws-sdk/client-lambda',
    '@aws-sdk/client-eventbridge',
    '@middy/core',
    '@smithy/signature-v4',
    '@aws-sdk/credential-providers',
    '@aws-crypto/sha256-js',
    '@opentelemetry/otlp-transformer',
    '@opentelemetry/sdk-trace-base',
    '@opentelemetry/sdk-logs',
    '@opentelemetry/sdk-metrics',
    '@opentelemetry/core',
  ],
  },
  target: false,
});
