import { defineConfig } from 'tsup';

export default defineConfig({
  entry: {
    index: 'src/index.ts',
    lambda: 'src/lambda.ts',
    'lambda-auto': 'src/lambda/auto.ts',
    sdk: 'src/sdk.ts',
    s3: 'src/s3.ts',
    dynamodb: 'src/dynamodb.ts',
    sqs: 'src/sqs.ts',
    sns: 'src/sns.ts',
    kinesis: 'src/kinesis.ts',
    'step-functions': 'src/step-functions.ts',
    eventbridge: 'src/eventbridge.ts',
    xray: 'src/xray.ts',
    testing: 'src/testing.ts',
    attributes: 'src/attributes.ts',
  },
  format: ['esm', 'cjs'],
  dts: true,
  sourcemap: true,
  outDir: 'dist',
  clean: true,
  treeshake: true,
  splitting: true,
  minify: false,
  external: [
    'autotel',
    '@aws-sdk/client-s3',
    '@aws-sdk/client-dynamodb',
    '@aws-sdk/client-sqs',
    '@aws-sdk/client-sns',
    '@aws-sdk/client-kinesis',
    '@aws-sdk/client-sfn',
    '@aws-sdk/client-lambda',
    '@aws-sdk/client-eventbridge',
    '@middy/core',
  ],
});
