/**
 * Drizzle ORM + Autotel — slow-query demo
 *
 * Long-running driver that interleaves fast Drizzle CRUD with an
 * occasional **genuinely-slow** SQL query (a recursive CTE that SQLite
 * actually executes — no setTimeout fakery). Shapes the trace stream so
 * autotel-mcp's anomaly + span-duration tools have something real to
 * investigate.
 *
 * Run it:
 *   pnpm db:push          # once, to create tables
 *   pnpm start            # runs until Ctrl-C
 *
 * Point autotel-mcp at the same OTLP receiver (Jaeger, Tempo, or
 * autotel-mcp's built-in collector on :4318) and try:
 *   find_anomalies service=drizzle-example
 *   search_spans serviceName=drizzle-example minDurationMs=300
 *   find_errors service=drizzle-example        (validation mistakes also surface)
 */

import 'dotenv/config';
import { init, trace, type TraceContext } from 'autotel';
import { instrumentDrizzleClient } from 'autotel-drizzle';
import { drizzle } from 'drizzle-orm/libsql';
import { createClient } from '@libsql/client';
import { eq, sql } from 'drizzle-orm';
import * as schema from './schema';

init({
  service: 'drizzle-example',
  endpoint: process.env.OTLP_ENDPOINT || 'http://localhost:4318',
});

const client = createClient({
  url: process.env.DATABASE_URL || 'file:./drizzle/dev.db',
});

const db = instrumentDrizzleClient(drizzle({ client, schema }), {
  dbSystem: 'sqlite',
});

const { users, posts } = schema;

// ---- Traced operations ---------------------------------------------------

export const createUser = trace(
  'createUser',
  (ctx) => async (email: string, name?: string) => {
    ctx.setAttribute('user.email', email);
    if (name) ctx.setAttribute('user.name', name);
    const [user] = await db.insert(users).values({ email, name }).returning();
    return user!;
  },
);

export const createPost = trace(
  'createPost',
  (ctx) => async (userId: number, title: string, content?: string) => {
    ctx.setAttribute('post.userId', userId);
    ctx.setAttribute('post.title', title);
    const [post] = await db
      .insert(posts)
      .values({ title, content, authorId: userId })
      .returning();
    return post!;
  },
);

export const getUserWithPosts = trace(
  'getUserWithPosts',
  (ctx) => async (userId: number) => {
    ctx.setAttribute('user.id', userId);
    const user = await db.query.users.findFirst({
      where: eq(users.id, userId),
      with: { posts: true },
    });
    if (user) ctx.setAttribute('user.postCount', user.posts.length);
    return user;
  },
);

export const publishPost = trace(
  'publishPost',
  (ctx) => async (postId: number) => {
    ctx.setAttribute('post.id', postId);
    const [post] = await db
      .update(posts)
      .set({ published: true })
      .where(eq(posts.id, postId))
      .returning();
    return post;
  },
);

/**
 * Deliberately slow read. Runs a recursive CTE that SQLite *actually*
 * executes — the span's duration and `db.statement` both reflect real
 * work, so latency-based MCP tools can pick it up.
 */
export const slowSearch = trace(
  'slowSearch',
  (ctx: TraceContext) => async (iterations: number) => {
    ctx.setAttribute('db.query.iterations', iterations);
    ctx.setAttribute('workload', 'slow-cte');
    // Recursive CTE: count from 1 to N. Scales linearly; tune `iterations`
    // at the call site for the desired latency.
    const rows = await db.all(sql`
      WITH RECURSIVE c(n) AS (
        SELECT 1
        UNION ALL
        SELECT n + 1 FROM c WHERE n < ${iterations}
      )
      SELECT count(*) as total FROM c
    `);
    return rows;
  },
);

// ---- Driver loop ---------------------------------------------------------

async function ensureSeeded(): Promise<number> {
  const existing = await db.query.users.findFirst({
    where: eq(users.email, 'demo@example.com'),
  });
  if (existing) return existing.id;
  const user = await createUser('demo@example.com', 'Demo User');
  await createPost(user.id, 'Seed post 1', 'Welcome to the demo.');
  await createPost(user.id, 'Seed post 2', 'Another post.');
  return user.id;
}

const delay = (ms: number) =>
  new Promise<void>((resolve) => setTimeout(resolve, ms));

function pickFastOp(userId: number): () => Promise<unknown> {
  const ops: Array<() => Promise<unknown>> = [
    () => getUserWithPosts(userId),
    () =>
      createPost(
        userId,
        `Post ${Date.now()}`,
        'Generated by the driver loop.',
      ),
    () => publishPost(Math.max(1, Math.floor(Math.random() * 10))),
  ];
  return ops[Math.floor(Math.random() * ops.length)]!;
}

async function driverLoop(): Promise<void> {
  const userId = await ensureSeeded();
  console.log(
    `🔁 Driver loop running against ${process.env.OTLP_ENDPOINT || 'http://localhost:4318'}. Ctrl-C to stop.`,
  );

  // Slow every Nth op; N=6 gives ~17% slow in the mix, enough for the
  // anomaly detector to treat them as outliers against fast baseline.
  const SLOW_EVERY = 6;
  let iteration = 0;

  // eslint-disable-next-line no-constant-condition
  while (true) {
    iteration++;
    const isSlow = iteration % SLOW_EVERY === 0;

    try {
      const start = Date.now();
      if (isSlow) {
        // Vary the slow-query cost so anomaly evidence is interesting.
        // SQLite recursion at this scale lands around 300-700ms on typical
        // dev hardware — dramatic enough for the demo without being tedious.
        const iters = 1_500_000 + Math.floor(Math.random() * 2_500_000);
        await slowSearch(iters);
        console.log(
          `🐢 [${iteration}] slowSearch(${iters}) took ${Date.now() - start}ms`,
        );
      } else {
        await pickFastOp(userId)();
        console.log(`⚡ [${iteration}] fast op took ${Date.now() - start}ms`);
      }
    } catch (err) {
      console.error(`💥 [${iteration}] op failed:`, err);
    }

    await delay(100 + Math.random() * 250);
  }
}

async function shutdown(): Promise<void> {
  console.log('\n⏳ Flushing traces…');
  // Give the BatchSpanProcessor time to export the tail.
  await delay(2000);
  try {
    client.close();
  } catch {
    /* already closed */
  }
  process.exit(0);
}

process.on('SIGINT', shutdown);
process.on('SIGTERM', shutdown);

driverLoop().catch((err) => {
  console.error('fatal:', err);
  process.exit(1);
});
